apiVersion: v1
kind: ConfigMap
metadata:
  name: php-fpm-config
data:
  www.conf: |
    php_admin_value[error_log] = /dev/stderr
    php_admin_flag[log_errors] = on

    ; Pass TZ environment variable to PHP
    env[TZ] = $TZ

    user = www-data
    group = www-data

    pm = static
    pm.process_idle_timeout = 10s;
    pm.max_children = 20;
    pm.max_requests = 500;