apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-backend-app

  template:
    metadata:
      annotations:
        checksum/php-fpm-config: {{ include (print $.Template.BasePath "/backend/php-fpm/php-fpm-configmap.yaml") . | sha256sum }}
        checksum/php-ini-config: {{ include (print $.Template.BasePath "/backend/php-fpm/php-ini-configmap.yaml") . | sha256sum }}
      labels:
        app: php-backend-app
    spec:
      serviceAccountName: registry-account
      containers:
        - name: php-fpm
          image: {{ .Values.backend.image | required "backend.image is required" }}
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/local/etc/php/conf.d/custom.ini
              name: php-ini-volume
              subPath: custom.ini
            - mountPath: /usr/local/etc/php-fpm.d/www.conf
              name: php-fpm-config
              subPath: www.conf # 특정 파일만 마운트, mountPath에도 존재해야함
            - mountPath: /session
              name: php-session-volume
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.username }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
          command:
            - php-fpm
      volumes:
        - name: php-fpm-config
          configMap:
            name: php-fpm-config
        - name: php-ini-volume
          configMap:
            name: php-ini-config
        - name: php-session-volume
          persistentVolumeClaim:
            claimName: insurance-db-php-session
