apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/backend/php-fpm-configmap.yaml") . | sha256sum }}

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app

  template:
    metadata:
      labels:
        app: backend-app
    spec:
      serviceAccountName: registry-account
      containers:
        - name: php-fpm
          image: {{ .Values.backend.image | required "backend.image is required" }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/local/etc/php-fpm.d/www.conf
              name: php-fpm-config
              subPath: www.conf # 특정 파일만 마운트, mountPath에도 존재해야함
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.username }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password

      volumes:
        - name: php-fpm-config
          configMap:
            name: php-fpm-config